In [1]:
print('Hello World')

Hello World


In [2]:
# Page 77
weight = 0.5
inp = 0.5
goal_prediction = 0.8

step_amount = 0.001

for i in range(1101):
    prediction = inp * weight
    error = (prediction - goal_prediction) ** 2
    
    print("Error: " + str(error) + " Prediction: " + str(prediction))
    
    up_prediction = inp * (weight + step_amount)
    up_error = (goal_prediction - up_prediction) ** 2
    
    down_prediction = inp * (weight - step_amount)
    down_error = (goal_prediction - down_prediction) ** 2
    
    if down_error < up_error:
        weight -= step_amount
    elif up_error < down_error:
        weight += step_amount

Error: 0.30250000000000005 Prediction: 0.25
Error: 0.3019502500000001 Prediction: 0.2505
Error: 0.30140100000000003 Prediction: 0.251
Error: 0.30085225 Prediction: 0.2515
Error: 0.30030400000000007 Prediction: 0.252
Error: 0.2997562500000001 Prediction: 0.2525
Error: 0.29920900000000006 Prediction: 0.253
Error: 0.29866224999999996 Prediction: 0.2535
Error: 0.29811600000000005 Prediction: 0.254
Error: 0.2975702500000001 Prediction: 0.2545
Error: 0.29702500000000004 Prediction: 0.255
Error: 0.29648025 Prediction: 0.2555
Error: 0.29593600000000003 Prediction: 0.256
Error: 0.2953922500000001 Prediction: 0.2565
Error: 0.294849 Prediction: 0.257
Error: 0.29430625 Prediction: 0.2575
Error: 0.293764 Prediction: 0.258
Error: 0.2932222500000001 Prediction: 0.2585
Error: 0.292681 Prediction: 0.259
Error: 0.29214025 Prediction: 0.2595
Error: 0.2916 Prediction: 0.26
Error: 0.2910602500000001 Prediction: 0.2605
Error: 0.29052100000000003 Prediction: 0.261
Error: 0.28998225 Prediction: 0.2615
Error: 

In [6]:
# Page 86
weight, goal_pred, inp = (0.0, 0.8, 1.1)
    
for iteration in range(4):
    print("---------\nWeight:" + str(weight))
    
    pred = inp * weight
    error = (pred - goal_pred) ** 2
    delta = pred - goal_pred
    weight_delta = delta * inp
    weight -= weight_delta
    
    print("Error:" + str(error) + " Prediction:" + str(pred))
    print("Delta:" + str(delta) + " Weight Delta:" + str(weight_delta))

---------
Weight:0.0
Error:0.6400000000000001 Prediction:0.0
Delta:-0.8 Weight Delta:-0.8800000000000001
---------
Weight:0.8800000000000001
Error:0.02822400000000005 Prediction:0.9680000000000002
Delta:0.16800000000000015 Weight Delta:0.1848000000000002
---------
Weight:0.6951999999999999
Error:0.0012446784000000064 Prediction:0.76472
Delta:-0.03528000000000009 Weight Delta:-0.0388080000000001
---------
Weight:0.734008
Error:5.4890317439999896e-05 Prediction:0.8074088
Delta:0.007408799999999993 Weight Delta:0.008149679999999992


In [21]:
# My own gradient-boosting after Chapter 4
inp = 100
weight = 0.5
goal_pred = 0.8

error = 1
alpha = 0.00009

count_of_iterations = 0

while error > 10 ** -12:
    count_of_iterations += 1
    
    pred = inp * weight
    error = (pred - goal_pred) ** 2
    
    boost = alpha * inp * (pred - goal_pred)
    weight -= boost
    
    print("Error: " + str(error) + "Prediction: " + str(pred))
    
print("Number of iterations: " + str(count_of_iterations))

Error: 2420.6400000000003Prediction: 50.0
Error: 24.20639999999992Prediction: 5.719999999999992
Error: 0.24206399999999867Prediction: 1.2919999999999987
Error: 0.0024206399999999913Prediction: 0.8492
Error: 2.4206399999999257e-05Prediction: 0.80492
Error: 2.420640000000472e-07Prediction: 0.8004920000000001
Error: 2.4206399999971946e-09Prediction: 0.8000492
Error: 2.4206399999644208e-11Prediction: 0.80000492
Error: 2.420639999636683e-13Prediction: 0.800000492
Number of iterations: 9


In [1]:
#New practice
hey_you = 'Hello Github'
print(hey_you)

Hello Github


In [2]:
# Page 138
import numpy as np

weights = np.array([0.5, 0.48, -0.7])
alpha = 0.1

streetlights = np.array( [[1, 0, 1],
                          [0, 1, 1],
                          [0, 0, 1],
                          [1, 1, 1],
                          [0, 1, 1], 
                          [1, 0, 1]] )

walk_vs_stop = np.array([0, 1, 0, 1, 1, 0])

inp = streetlights[0]
goal_pred = walk_vs_stop[0]

for i in range(40):
    error_for_all_lights = 0
    
    for row_index in range(len(walk_vs_stop)):
        inp = streetlights[row_index]
        goal_pred = walk_vs_stop[row_index]
        
        pred = inp.dot(weights)
        
        error = (goal_pred - pred) ** 2
        error_for_all_lights += error
        
        delta = pred - goal_pred
        weights -= alpha * (inp * delta)
        # print('Prediction: {}'.format(pred))
        
    print('Error: {}'.format(error_for_all_lights))
    

Error: 2.6561231104
Error: 0.9628701776715985
Error: 0.5509165866836797
Error: 0.36445836852222424
Error: 0.2516768662079895
Error: 0.17797575048089034
Error: 0.12864460733422164
Error: 0.09511036950476208
Error: 0.07194564247043436
Error: 0.05564914990717743
Error: 0.04394763937673939
Error: 0.035357967050948465
Error: 0.02890700056547436
Error: 0.023951660591138853
Error: 0.020063105176016144
Error: 0.016952094519447087
Error: 0.014420818295271236
Error: 0.012331739998443648
Error: 0.010587393171639842
Error: 0.009117233405426495
Error: 0.00786904226904208
Error: 0.006803273214640502
Error: 0.005889303541837786
Error: 0.0051029252561172675
Error: 0.004424644608684828
Error: 0.0038385124412518303
Error: 0.0033313054558089675
Error: 0.0028919416227737734
Error: 0.002511053608117256
Error: 0.0021806703520253884
Error: 0.0018939739123713475
Error: 0.0016451096996342332
Error: 0.0014290353984827077
Error: 0.0012413985592149145
Error: 0.0010784359268087556
Error: 0.0009368896209360312
Erro

In [6]:
# Page 157 (162)

import numpy as np

np.random.seed(1)

def relu(x):
    return (x > 0) * x

def relu2deriv(output):
    return output > 0

alpha = 0.2
hidden_size = 4

streetlights = np.array( [[1, 0, 1],
                          [0, 1, 1],
                          [0, 0, 1],
                          [1, 1, 1],
                          [0, 1, 1], 
                          [1, 0, 1]] )

walk_vs_stop = np.array([0, 1, 0, 1, 1, 0])

weights_0_1 = 2 * np.random.random((3, hidden_size)) - 1
weights_1_2 = 2 * np.random.random((hidden_size, 1)) - 1

# print(weights_0_1)

for iteration in range(60):
    layer_2_error = 0
    for i in range(len(streetlights)):
        layer_0 = streetlights[i:i+1]
        layer_1 = relu(np.dot(layer_0, weights_0_1))
        layer_2 = np.dot(layer_1, weights_1_2)
        
        layer_2_error += np.sum((layer_2 - walk_vs_stop[i:i+1]) ** 2)
        
        layer_2_delta = layer_2 - walk_vs_stop[i:i+1]
        layer_1_delta = layer_2_delta.dot(weights_1_2.T) * relu2deriv(layer_1)
        
        weights_1_2 -= alpha * layer_1.T.dot(layer_2_delta)
        weights_0_1 -= alpha * layer_0.T.dot(layer_1_delta)
        
    if (iteration % 10 == 9): # Эта строка вычисляет разность в слое
        print ("Error:" + str(layer_2_error))

Error:0.31298811341557736
Error:0.043272385299784624
Error:0.0034372657015086937
Error:0.00019649599346773566
Error:1.015593230102771e-05
Error:5.122102420300414e-07


In [9]:
#import numpy as np
# Test
lights = np.array( [[1, 0, 1],
                    [0, 1, 1],
                    [0, 0, 1],
                    [1, 1, 1],
                    [0, 1, 1], 
                    [1, 0, 1]] )

print(lights[4:5] > 0)

[[False  True  True]]


In [6]:
# Page 180 - 190
import sys
import numpy as np
from keras.datasets import mnist

np.random.seed(1)
(x_train, y_train), (x_test, y_test) = mnist.load_data()

images, labels = (x_train[0:1000].reshape(1000, 28*28) /\
                                     255, y_train[0:1000])
one_hot_labels = np.zeros((len(labels), 10))

for i, l in enumerate(labels):
    one_hot_labels[i][l] = 1
labels = one_hot_labels

test_images = x_test.reshape(len(x_test), 28*28) / 255
test_labels = np.zeros((len(y_test), 10))
for i, l in enumerate(y_test):
    test_labels[i][l] = 1
    
relu = lambda x: (x >= 0) * x
relu2deriv = lambda output: output >= 0

alpha, iterations, hidden_size = (0.005, 350, 40)
pixels_per_image, num_labels = (784, 10)

weights_0_1 = 0.2 * np.random.random((pixels_per_image, hidden_size)) - 0.1
weights_1_2 = 0.2 * np.random.random((hidden_size, num_labels)) - 0.1

for j in range(iterations):
    error, correct_cnt = (0.0, 0)
    
    for i in range(len(images)):
        layer_0 = images[i:i+1]
        layer_1 = relu(np.dot(layer_0, weights_0_1))

        # Маска прореживания (регуляризация)
        dropout_mask = np.random.randint(2, size=layer_1.shape)
        # Прореживаем первый слой
        layer_1 *= dropout_mask * 2
        
        layer_2 = np.dot(layer_1, weights_1_2)
        
        error += np.sum((labels[i:i+1] - layer_2) ** 2)
        correct_cnt += int(np.argmax(layer_2) == \
                                              np.argmax(labels[i:i+1]))
        
        layer_2_delta = (labels[i:i+1] - layer_2)
        layer_1_delta = layer_2_delta.dot(weights_1_2.T)\
                                        * relu2deriv(layer_1)
        # Добавляем прореживание в Back-Propagation
        layer_1_delta *= dropout_mask
        
        weights_1_2 += alpha * layer_1.T.dot(layer_2_delta)
        weights_0_1 += alpha * layer_0.T.dot(layer_1_delta)
    
    if (j % 10 == 0):
        test_error = 0.0
        test_correct_cnt = 0
        
        for i in range(len(test_images)):
            layer_0 = test_images[i:i+1]
            layer_1 = relu(np.dot(layer_0, weights_0_1))
            layer_2 = np.dot(layer_1, weights_1_2)
            
            test_error += np.sum((test_labels[i:i+1] - layer_2) ** 2)
            test_correct_cnt += int(np.argmax(layer_2) == \
                                   np.argmax(test_labels[i:i+1]))
        
        sys.stdout.write('\n' + \
            'I:' + str(j) + \
            ' Test-Err:' + str(test_error/float(len(test_images)))[0:5] +\
            ' Test-Acc:' + str(test_correct_cnt/float(len(test_images))) +\
            ' Train-Err:' + str(error/float(len(images)))[0:5] +\
            ' Train-Err:' + str(correct_cnt/float(len(images))))


I:0 Test-Err:0.718 Test-Acc:0.5418 Train-Err:0.885 Train-Err:0.289
I:10 Test-Err:0.501 Test-Acc:0.7365 Train-Err:0.564 Train-Err:0.647
I:20 Test-Err:0.478 Test-Acc:0.7621 Train-Err:0.530 Train-Err:0.681
I:30 Test-Err:0.457 Test-Acc:0.7915 Train-Err:0.508 Train-Err:0.71
I:40 Test-Err:0.445 Test-Acc:0.7998 Train-Err:0.492 Train-Err:0.719
I:50 Test-Err:0.430 Test-Acc:0.8145 Train-Err:0.462 Train-Err:0.742
I:60 Test-Err:0.446 Test-Acc:0.7974 Train-Err:0.472 Train-Err:0.746
I:70 Test-Err:0.445 Test-Acc:0.7901 Train-Err:0.463 Train-Err:0.744
I:80 Test-Err:0.426 Test-Acc:0.8105 Train-Err:0.461 Train-Err:0.764
I:90 Test-Err:0.435 Test-Acc:0.7871 Train-Err:0.462 Train-Err:0.749
I:100 Test-Err:0.433 Test-Acc:0.8039 Train-Err:0.452 Train-Err:0.769
I:110 Test-Err:0.435 Test-Acc:0.8099 Train-Err:0.439 Train-Err:0.778
I:120 Test-Err:0.442 Test-Acc:0.7871 Train-Err:0.451 Train-Err:0.778
I:130 Test-Err:0.439 Test-Acc:0.811 Train-Err:0.452 Train-Err:0.783
I:140 Test-Err:0.443 Test-Acc:0.8049 Train-Err

# New Activation Functions such as tanh, softmax and their backprop versions

In [1]:
# Page 212-214 - We are investigating new activation functions

import numpy as np, sys
np.random.seed(1)


from keras.datasets import mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()

images, labels = (x_train[0:1000].reshape(1000,28*28)\
                                                 / 255, y_train[0:1000])

In [2]:
#2 Page 212-214 - We are investigating new activation functions

one_hot_labels = np.zeros((len(labels), 10))
for i, l in enumerate(labels):
    one_hot_labels[i][l] = 1
labels = one_hot_labels

test_images = x_test.reshape(len(x_test), 28*28) / 255
test_labels = np.zeros((len(y_test), 10))
for i, l in enumerate(y_test):
    test_labels[i][l] = 1

In [4]:
#3 Page 212-214 - We are investigating new activation functions

def tanh(x):
    return np.tanh(x)

def tanh2deriv(output):
    return 1 - (output ** 2)

def softmax(x):
    temp = np.exp(x)
    return temp / np.sum(temp, axis=1, keepdims=True)
    
alpha, iterations, hidden_size = (2, 300, 100)
pixels_per_image, num_labels = (784, 10)
batch_size = 100

weights_0_1 = 0.02 * np.random.random((pixels_per_image, hidden_size)) - 0.01
weights_1_2 = 0.2 * np.random.random((hidden_size, num_labels)) - 0.1

In [5]:
#4 Page 212-214 - We are investigating new activation functions

for j in range(iterations):
    correct_cnt = 0
    for i in range(int(len(images) / batch_size)):
        batch_start, batch_end = ((i * batch_size), ((i+1) * batch_size))
        layer_0 = images[batch_start:batch_end]
        layer_1 = tanh(np.dot(layer_0, weights_0_1))
        
        dropout_mask = np.random.randint(2, size=layer_1.shape)
        layer_1 *= dropout_mask * 2
        layer_2 = softmax(np.dot(layer_1, weights_1_2))
        
        for k in range(batch_size):
            correct_cnt += int(np.argmax(layer_2[k:k+1]) == \
                              np.argmax(labels[batch_start+k:batch_start+k+1]))
        
        layer_2_delta = (labels[batch_start:batch_end]-layer_2) \
                        / (batch_size * layer_2.shape[0])
        layer_1_delta = layer_2_delta.dot(weights_1_2.T) \
                        * tanh2deriv(layer_1)
        layer_1_delta *= dropout_mask
        
        weights_1_2 += alpha * layer_1.T.dot(layer_2_delta)
        weights_0_1 += alpha * layer_0.T.dot(layer_1_delta)
    
    test_correct_cnt = 0
    
    for i in range(len(test_images)):
        layer_0 = test_images[i:i+1]
        layer_1 = tanh(np.dot(layer_0, weights_0_1))
        layer_2 = np.dot(layer_1, weights_1_2)
        test_correct_cnt += int(np.argmax(layer_2) == \
                              np.argmax(test_labels[i:i+1]))
        
    if (j % 10 == 0):
        sys.stdout.write("\n"+ "I:" + str(j) + \
        " Test-Acc:"+str(test_correct_cnt/float(len(test_images)))+\
        " Train-Acc:" + str(correct_cnt/float(len(images))))


I:0 Test-Acc:0.394 Train-Acc:0.156
I:10 Test-Acc:0.6867 Train-Acc:0.723
I:20 Test-Acc:0.7025 Train-Acc:0.732
I:30 Test-Acc:0.734 Train-Acc:0.763
I:40 Test-Acc:0.7663 Train-Acc:0.794
I:50 Test-Acc:0.7913 Train-Acc:0.819
I:60 Test-Acc:0.8102 Train-Acc:0.849
I:70 Test-Acc:0.8228 Train-Acc:0.864
I:80 Test-Acc:0.831 Train-Acc:0.867
I:90 Test-Acc:0.8364 Train-Acc:0.885
I:100 Test-Acc:0.8407 Train-Acc:0.883
I:110 Test-Acc:0.845 Train-Acc:0.891
I:120 Test-Acc:0.8481 Train-Acc:0.901
I:130 Test-Acc:0.8505 Train-Acc:0.901
I:140 Test-Acc:0.8526 Train-Acc:0.905
I:150 Test-Acc:0.8555 Train-Acc:0.914
I:160 Test-Acc:0.8577 Train-Acc:0.925
I:170 Test-Acc:0.8596 Train-Acc:0.918
I:180 Test-Acc:0.8619 Train-Acc:0.933
I:190 Test-Acc:0.863 Train-Acc:0.933
I:200 Test-Acc:0.8642 Train-Acc:0.926
I:210 Test-Acc:0.8653 Train-Acc:0.931
I:220 Test-Acc:0.8668 Train-Acc:0.93
I:230 Test-Acc:0.8672 Train-Acc:0.937
I:240 Test-Acc:0.8681 Train-Acc:0.938
I:250 Test-Acc:0.8687 Train-Acc:0.937
I:260 Test-Acc:0.8684 Train-

# Convolutional neural networks

In [6]:
# Page 221-223 - We are investigating convolutional neural networks

import numpy as np, sys
np.random.seed(1)

from keras.datasets import mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [7]:
#2 Page 221-223 - We are investigating convolutional neural networks

images, labels = (x_train[0:1000].reshape(1000, 28*28) / 255,
                  y_train[0:1000])

one_hot_labels = np.zeros((len(labels), 10))
for i, l in enumerate(labels):
    one_hot_labels[i][l] = 1
labels = one_hot_labels

test_images = x_test.reshape(len(x_test), 28*28) / 255
test_labels = np.zeros((len(y_test), 10))
for i, l in enumerate(y_test):
    test_labels[i][l] = 1

In [8]:
#3 Page 221-223 - We are investigating convolutional neural networks

def tanh(x):
    return np.tanh(x)

def tanh2deriv(output):
    return 1 - (output ** 2)

def softmax(x):
    temp = np.exp(x)
    return temp / np.sum(temp, axis=1, keepdims=True)

alpha, iterations = (2, 300)
pixels_per_image, num_labels = (784, 10)
batch_size = 128

input_rows = 28
input_cols = 28

kernel_rows = 3
kernel_cols = 3
num_kernels = 16

hidden_size = ((input_rows - kernel_rows) *
              (input_cols - kernel_cols)) * num_kernels

kernels = 0.02 * np.random.random((kernel_rows * kernel_cols,
                                 num_kernels)) - 0.01

weights_1_2 = 0.2 * np.random.random((hidden_size,
                                     num_labels)) - 0.1

def get_image_section(layer, row_from, row_to, col_from, col_to):
    section = layer[:, row_from:row_to, col_from:col_to]
    return section.reshape(-1, 1, row_to-row_from, col_to-col_from)

In [11]:
#4 Page 221-223 - We are investigating convolutional neural networks

for j in range(iterations):
    correct_cnt = 0
    for i in range(int(len(images) / batch_size)):
        batch_start, batch_end = ((i*batch_size), ((i+1)*batch_size))
        layer_0 = images[batch_start:batch_end]
        layer_0 = layer_0.reshape(layer_0.shape[0], 28, 28)
        layer_0.shape
        
        sects = list()
        for row_start in range(layer_0.shape[1] - kernel_rows):
            for col_start in range(layer_0.shape[2] - kernel_rows):
                sect = get_image_section(layer_0,
                                        row_start,
                                        row_start+kernel_rows,
                                        col_start,
                                        col_start+kernel_cols)
                sects.append(sect)
        
        expanded_input = np.concatenate(sects, axis=1)
        es = expanded_input.shape
        flattened_input = expanded_input.reshape(es[0]*es[1], -1)
        
        kernel_output = flattened_input.dot(kernels)
        layer_1 = tanh(kernel_output.reshape(es[0],-1))
        dropout_mask = np.random.randint(2, size=layer_1.shape)
        layer_1 *= dropout_mask * 2
        layer_2 = softmax(np.dot(layer_1, weights_1_2))
        
        for k in range(batch_size):
            labelset = labels[batch_start+k:batch_start+k+1]
            _inc = int(np.argmax(layer_2[k:k+1]) == 
                      np.argmax(labelset))
            correct_cnt += _inc
            
        layer_2_delta = (labels[batch_start:batch_end] - layer_2) \
                        / (batch_size * layer_2.shape[0])
        layer_1_delta = layer_2_delta.dot(weights_1_2.T) * \
                        tanh2deriv(layer_1)
        layer_1_delta *= dropout_mask
        
        weights_1_2 += alpha * layer_1.T.dot(layer_2_delta)
        l1d_reshape = layer_1_delta.reshape(kernel_output.shape)
        k_update = flattened_input.T.dot(l1d_reshape)
        kernels -= alpha * k_update
        
    
    test_correct_cnt = 0
    
    for i in range(len(test_images)):
        layer_0 = test_images[i:i+1]
        layer_0 = layer_0.reshape(layer_0.shape[0], 28, 28)
        layer_0.shape
        
        sects = list()
        for row_start in range(layer_0.shape[1] - kernel_rows):
            for col_start in range(layer_0.shape[2] - kernel_rows):
                sect = get_image_section(layer_0,
                                        row_start,
                                        row_start+kernel_rows,
                                        col_start,
                                        col_start+kernel_cols)
                sects.append(sect)
        
        expanded_input = np.concatenate(sects, axis=1)
        es = expanded_input.shape
        flattened_input = expanded_input.reshape(es[0]*es[1], -1)
        
        kernel_output = flattened_input.dot(kernels)
        layer_1 = tanh(kernel_output.reshape(es[0],-1))
        layer_2 = np.dot(layer_1, weights_1_2)
        
        test_correct_cnt += int(np.argmax(layer_2) == 
                              np.argmax(test_labels[i:i+1]))
    
    if (j % 1 == 0):
        sys.stdout.write("\n" + \
        "I:" + str(j) + \
        " Test-Acc:" + str(test_correct_cnt/float(len(test_images)))+\
        " Train-Acc:" + str(correct_cnt/float(len(images))))


I:0 Test-Acc:0.4023 Train-Acc:0.209
I:1 Test-Acc:0.4358 Train-Acc:0.238
I:2 Test-Acc:0.4473 Train-Acc:0.286
I:3 Test-Acc:0.4389 Train-Acc:0.274
I:4 Test-Acc:0.3951 Train-Acc:0.257
I:5 Test-Acc:0.2222 Train-Acc:0.243
I:6 Test-Acc:0.0613 Train-Acc:0.112
I:7 Test-Acc:0.0266 Train-Acc:0.035
I:8 Test-Acc:0.0127 Train-Acc:0.026
I:9 Test-Acc:0.0133 Train-Acc:0.022
I:10 Test-Acc:0.0185 Train-Acc:0.038
I:11 Test-Acc:0.0363 Train-Acc:0.038
I:12 Test-Acc:0.0928 Train-Acc:0.067
I:13 Test-Acc:0.1994 Train-Acc:0.081
I:14 Test-Acc:0.3086 Train-Acc:0.154
I:15 Test-Acc:0.4276 Train-Acc:0.204
I:16 Test-Acc:0.5323 Train-Acc:0.256
I:17 Test-Acc:0.5919 Train-Acc:0.305
I:18 Test-Acc:0.6324 Train-Acc:0.341
I:19 Test-Acc:0.6608 Train-Acc:0.426
I:20 Test-Acc:0.6815 Train-Acc:0.439
I:21 Test-Acc:0.7048 Train-Acc:0.462
I:22 Test-Acc:0.7171 Train-Acc:0.484
I:23 Test-Acc:0.7313 Train-Acc:0.505
I:24 Test-Acc:0.7355 Train-Acc:0.53
I:25 Test-Acc:0.7417 Train-Acc:0.548
I:26 Test-Acc:0.747 Train-Acc:0.534
I:27 Test-Ac

# NLP Start

In [1]:
# Some preprocessing work not in the book
filenames = ['reviews #1.txt', 'reviews #2.txt']
with open('reviews.txt', 'w') as outfile:
    for fname in filenames:
        with open(fname) as infile:
            outfile.write(infile.read())

In [2]:
# Page 214 - preprocessing

import sys

f = open('reviews.txt')
raw_reviews = f.readlines()
f.close()

f = open('labels.txt')
raw_labels = f.readlines()
f.close()

tokens = list(map(lambda x:set(x.split(' ')), raw_reviews))

vocab = set()
for sent in tokens:
    for word in sent:
        if (len(word) > 0):
            vocab.add(word)
vocab = list(vocab)

word2index = {}
for i, word in enumerate(vocab):
    word2index[word] = i
    
input_dataset = list()
for sent in tokens:
    sent_indices = list()
    for word in sent:
        try:
            sent_indices.append(word2index[word])
        except:
            ''
    input_dataset.append(list(set(sent_indices)))
    
target_dataset = list()
for label in raw_labels:
    if label == 'positive\n':
        target_dataset.append(1)
    else:
        target_dataset.append(0)

In [3]:
# Page 216

import numpy as np
np.random.seed(1)

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

alpha, iterations = (0.01, 2)
hidden_size = 100

weights_0_1 = 0.2*np.random.random((len(vocab),hidden_size)) - 0.1
weights_1_2 = 0.2*np.random.random((hidden_size,1)) - 0.1

correct,total = (0,0)
for iter in range(iterations):
    for i in range(len(input_dataset)-1000):
        
        x, y = (input_dataset[i], target_dataset[i])
        layer_1 = sigmoid(np.sum(weights_0_1[x], axis=0))
        layer_2 = sigmoid(np.dot(layer_1, weights_1_2))
        
        layer_2_delta = layer_2 - y
        layer_1_delta = layer_2_delta.dot(weights_1_2.T)
        
        weights_0_1[x] -= layer_1_delta * alpha
        weights_1_2 -= np.outer(layer_1, layer_2_delta) * alpha
        
        if(np.abs(layer_2_delta) < 0.5):
            correct += 1
        total += 1
        if(i % 10 == 9):
            progress = str(i/float(len(input_dataset)))
            sys.stdout.write('\rIter:'+str(iter)\
                            +' Progress:'+progress[2:4]\
                            +'.'+progress[4:6]\
                            +'% Training Accuracy:'\
                            + str(correct/float(total)) + '%')
    print()
correct, total = (0,0)
for i in range(len(input_dataset)-1000,len(input_dataset)):
    x = input_dataset[i]
    y = target_dataset[i]
    
    layer_1 = sigmoid(np.sum(weights_0_1[x],axis=0))
    layer_2 = sigmoid(np.dot(layer_1,weights_1_2))
    
    if(np.abs(layer_2 - y) < 0.5):
        correct += 1
    total += 1
print("Test Accuracy:" + str(correct / float(total)))

Iter:0 Progress:95.95% Training Accuracy:0.7971654856190079%%
Iter:1 Progress:95.95% Training Accuracy:0.8195211402613098%
Test Accuracy:0.843


# Substitution of missing words

In [2]:
# Page 243 - preprocessing step
import sys,random,math
from collections import Counter
import numpy as np

np.random.seed(1)

f = open('reviews.txt')
raw_reviews = f.readlines()
f.close()

tokens = list(map(lambda x:(x.split(" ")),raw_reviews))
wordcnt = Counter()
for sent in tokens:
    for word in sent:
        wordcnt[word] -= 1
vocab = list(set(map(lambda x:x[0],wordcnt.most_common())))
                                    
word2index = {}
for i, word in enumerate(vocab):
    word2index[word] = i
                                    
  
concatenated = list()
input_dataset = list()
for sent in tokens:
    sent_indices = list()
    for word in sent:
        try:
            sent_indices.append(word2index[word])
            concatenated.append(word2index[word])
        except:
            ""
    input_dataset.append(sent_indices)
concatenated = np.array(concatenated)

In [3]:
# Page 243-244

random.shuffle(input_dataset)
alpha, iterations = (0.05, 2)
hidden_size, window, negative = (50, 2, 5)

weights_0_1 = (np.random.rand(len(vocab),hidden_size) - 0.5) * 0.2
weights_1_2 = np.random.rand(len(vocab),hidden_size) * 0.2

layer_2_target = np.zeros(negative+1)
layer_2_target[0] = 1

def similar(target='beautiful'):
    target_index = word2index[target]
    
    scores = Counter()
    for word, index in word2index.items():
        raw_difference = weights_0_1[index] - (weights_0_1[target_index])
        squared_difference = raw_difference * raw_difference
        scores[word] = - math.sqrt(sum(squared_difference))
    return scores.most_common(10)

def sigmoid(x):
    return 1/(1 + np.exp(-x))

for rev_i, review in enumerate(input_dataset * iterations):
    for target_i in range(len(review)):

        target_samples = [review[target_i]]+list(concatenated\
            [(np.random.rand(negative)*len(concatenated)).astype('int').tolist()])

        left_context = review[max(0,target_i-window):target_i]
        right_context = review[target_i+1:min(len(review),target_i+window)]

        layer_1 = np.mean(weights_0_1[left_context+right_context],axis=0)
        layer_2 = sigmoid(layer_1.dot(weights_1_2[target_samples].T))
        layer_2_delta = layer_2 - layer_2_target
        layer_1_delta = layer_2_delta.dot(weights_1_2[target_samples])

        weights_0_1[left_context+right_context] -= layer_1_delta * alpha
        weights_1_2[target_samples] -= np.outer(layer_2_delta,layer_1)*alpha

    if(rev_i % 250 == 0):
        sys.stdout.write('\rProgress:'+str(rev_i/float(len(input_dataset)
            *iterations)) + " " + str(similar('terrible')))
    sys.stdout.write('\rProgress:'+str(rev_i/float(len(input_dataset)
            *iterations)))
        
print(similar('terrible'))

Progress:0.9999799991999689 [('terrible', -0.0), ('horrible', -2.52559168953348), ('fantastic', -3.93465090925655), ('bad', -4.051182051722724), ('brilliant', -4.154160608588459), ('pathetic', -4.211284441468548), ('dreadful', -4.283776633630338), ('poor', -4.380962727928457), ('magnificent', -4.382881495844147), ('great', -4.401655404772276)]5)]58)]9)]]5)])])]]]]])])][('terrible', -0.0), ('horrible', -2.6096546786637247), ('bad', -3.767183518137911), ('fantastic', -3.875075043677378), ('brilliant', -3.991796014301944), ('pathetic', -4.10884763219456), ('dreadful', -4.243173950738017), ('stupid', -4.338180291179504), ('poor', -4.344969143714373), ('great', -4.373188116606074)]


# Neural networks that write like Shakespeare: recurrent layers for variable-length data

In [10]:
# Page 256

# import numpy as np

norms = np.sum(weights_0_1 * weights_0_1, axis=1)
norms.resize(norms.shape[0], 1)
normed_weights = weights_0_1 * norms

def make_sent_vect(words):
    indices = list(map(lambda x:word2index[x], \
                filter(lambda x: x in word2index, words)))
    return np.mean(normed_weights[indices], axis=0)

reviews2vectors = list()
for review in tokens:
    reviews2vectors.append(make_sent_vect(review))
reviews2vectors = np.array(reviews2vectors)

def most_similar_reviews(review):
    v = make_sent_vect(review)
    scores = Counter()
    for i, val in enumerate(reviews2vectors.dot(v)):
        scores[i] = val
    most_similar = list()
    for idx, score in scores.most_common(3):
        most_similar.append(raw_reviews[idx][0:40])
    return most_similar

most_similar_reviews(['boring','awful'])

['i don  t know why i like this movie so w',
 'this movie is so bad  i knew how it ends',
 'probably new zealands worst movie ever m']

In [7]:
# Page 262-263 identity matrix Practice

# import numpy as np

a = np.array([1, 2, 3])
b = np.array([0.1, 0.2, 0.3])
c = np.array([-1, -0.5, 0])
d = np.array([0, 0, 0])

identity = np.eye(3)
print(identity)

print(a.dot(identity))
print(b.dot(identity))
print(c.dot(identity))
print(d.dot(identity))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[1. 2. 3.]
[0.1 0.2 0.3]
[-1.  -0.5  0. ]
[0. 0. 0.]


In [6]:
# Page 263

this = np.array([2, 4, 6])
movie = np.array([10, 10, 10])
rocks = np.array([1, 1, 1])

print(this + movie + rocks)
print((this.dot(identity) + movie).dot(identity) + rocks)

[13 15 17]
[13. 15. 17.]


In [11]:
# Page 267

import numpy as np

def softmax(x_):
    x = np.atleast_2d(x_)
    temp = пр.ехр(х)
    return temp / np.sum(temp, axis=1, keepdims=True)

word_vects = {}
word_vects['yankees'] = np.array([[0., 0., 0.]])
word_vects['bears'] = np.array([[0., 0., 0.]])
word_vects['braves'] = np.array([[0., 0., 0.]])
word_vects['red'] = np.array([[0., 0., 0.]])
word_vects['sox'] = np.array([[0., 0., 0.]])
word_vects['lose'] = np.array([[0., 0., 0.]])
word_vects['defeat'] = np.array([[0., 0., 0.]])
word_vects['beat'] = np.array([[0., 0., 0.]])
word_vects['tie'] = np.array([[0., 0., 0.]])

sent2output = np.random.rand(3, len(word_vects))

identity = np.eye(3)

In [13]:
# Page 267 - creating layers for forward prop.

layer_0 = word_vects['red']
layer_1 = layer_0.dot(identity) + word_vects['sox']
layer_2 = layer_1.dot(identity) + word_vects['defeat']